// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const verifire = artifacts.require('Verifier');
const correctProof = require("../../zokrates/code/square/proof.json");

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

contract('TestVerifier', accs => {
    const owner = accounts[0];

    describe('testing verifier', function() {
        beforeEach(async function() {
            this.contract = await verifire.new( {from: owner} );
        })
        it('test verification with correct proof', async function() {
            let correctProofResult = await this.contract.verifyTx.call(correctProof.proof, correctProof.inputs);
            assert.equal(correctProofResult, true, "correct proof does not verify")
        })
    })
})
    
// Test verification with incorrect proof
